USE feedback_db;

CREATE DATABASE IF NOT EXISTS feedback_db;

CREATE TABLE IF NOT EXISTS feedback(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_NAME VARCHAR(20),
    EMAIL VARCHAR(20),
    COMMENTS TEXT,
    SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);